# Project-wide Gradle settings.

# AndroidX package structure
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style
kotlin.code.style=official

# Gradle JVM args
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable parallel build
org.gradle.parallel=true

# Enable caching
org.gradle.caching=true


# SSL
org.gradle.jvmargs=-Djavax.net.ssl.trustStore=/data/java/java-17-openjdk-amd64/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.trustStoreType=JKS -Xmx2048m -Dfile.encoding=UTF-8
